SCREEN_WIDTH = 720
SCREEN_HEIGHT = 750
FLOOR = 590

BUTTON_WIDTH = 180
BUTTON_HEIGHT = 100
BUTTON_X_MARGIN = 25
BUTTON_Y_MARGIN = 10
BUTTON_PEN_POSITION = [BUTTON_X_MARGIN, FLOOR + BUTTON_Y_MARGIN, BUTTON_WIDTH, BUTTON_HEIGHT]
BUTTON_PEN_TEXT_POSITION = [BUTTON_X_MARGIN + BUTTON_WIDTH / 3, FLOOR + BUTTON_Y_MARGIN + BUTTON_HEIGHT /3]
BUTTON_PENCIL_POSITION = [(3 * BUTTON_X_MARGIN) + BUTTON_WIDTH, FLOOR + BUTTON_Y_MARGIN, BUTTON_WIDTH, BUTTON_HEIGHT]
BUTTON_PENCIL_TEXT_POSITION = [(3 * BUTTON_X_MARGIN) +  (4 *BUTTON_WIDTH / 3), FLOOR + BUTTON_Y_MARGIN + BUTTON_HEIGHT /3]
BUTTON_VAL_POSITION = [(5 * BUTTON_X_MARGIN) + (2 * BUTTON_WIDTH), FLOOR + BUTTON_Y_MARGIN, BUTTON_WIDTH, BUTTON_HEIGHT]
BUTTON_VAL_TEXT_POSITION = [(5 * BUTTON_X_MARGIN) +  (7 *BUTTON_WIDTH / 3), FLOOR + BUTTON_Y_MARGIN + BUTTON_HEIGHT /3]
BUTTON_LINE_WIDTH = 5
BUTTON_LINE_COLOR = "black"

SQUARE_SIDE = 60
BOARD_MARGIN_X = 90
BOARD_MARGIN_Y = 25
INNER_THICK = 1
MEDIUM_THICK = 3
OUTER_THICK = 5
FOCUS_THICK = 7

PEN_HEIGHT = 40
PENCIL_HEIGTH = 10
PENCIL_MARGIN = 5

GAME_MODE_XY = (BOARD_MARGIN_X, SCREEN_HEIGHT - 35)
FILLING_MODE_XY = (SCREEN_WIDTH - 300, SCREEN_HEIGHT - 35)
FILLING_MODE_RECT = (SCREEN_WIDTH - 300, SCREEN_HEIGHT - 35, 300, 35)

NUMBERS_SET = {1, 2, 3, 4, 5, 6, 7, 8, 9}