SCREEN_WIDTH = 720
SCREEN_HEIGHT = 820
FLOOR = 590

BUTTON_WIDTH = 300
BUTTON_HEIGHT = 100
BUTTON_X_MARGIN = 30
BUTTON_Y_MARGIN = 10
BUTTON_PEN_POSITION = [BUTTON_X_MARGIN, FLOOR + BUTTON_Y_MARGIN, BUTTON_WIDTH, BUTTON_HEIGHT]
BUTTON_PENCIL_POSITION = [(3 * BUTTON_X_MARGIN) + BUTTON_WIDTH, FLOOR + BUTTON_Y_MARGIN, BUTTON_WIDTH, BUTTON_HEIGHT]

SQUARE_SIDE = 60

NORMAL_HEIGHT = 40
PENCIL_HEIGTH = 10

NUMBERS_SET = {1, 2, 3, 4, 5, 6, 7, 8, 9}